application: citygoround-hrd
version: 1-3-0-redfin-footer
runtime: python
api_version: 1

handlers:

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

# This was removed by dave -- gaeunit appears to depend on
# undocumented GAE APIs that were recently removed.
# CONSIDER upgrading gae?
# - url: /admin/test.*
#   script: gaeunit.py
#   login: admin

- url: /admin/.*
  script: bootstrap.py
  login: admin

- url: /(.*)
  script: bootstrap.py
